 const ActionTypes = {
     CURRENTUSER: 'CURRENTUSER',
     CURRENTCOMPANY: 'CURRENTCOMPANY',
     ADMINLOGIN: 'ADMINLOGIN',
     SHOWDATACOMPANY: 'SHOWDATACOMPANY',
     SHOWDATASTUDENT: 'SHOWDATASTUDENT',
     SHOWCOMPANYJOBS: 'SHOWCOMPANYJOBS',
     JOBCOMPANY: 'JOBCOMPANY',
     JOBCOMPANYUID: 'JOBCOMPANYUID',
     AUTHED: 'AUTHED'
     

     //  USERNAME: 'USERNAME',
     //  ALLUSERS: 'ALLUSERS',
     //  MESSAGES: 'MESSAGES',
     //  CHANGERECPUID: 'CHANGERECPUID',

 }

 export default ActionTypes;